title: Brendan Lobo

author:
  name: Brendan Lobo
  email: b.lobo@mail.utoronto.ca

theme: minima

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/Brendan-Lobo" }
    - { platform: linkedin, user_url: "https://ca.linkedin.com/in/brendanrlobo" }

header_pages:
  - Curriculum_Vitae.md
  - Projects.md
  - Publications.md

